<a href="https://colab.research.google.com/github/FreMeli/Colab/blob/main/Copia_de_T9_Tarea_pr%C3%A1ctica.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Alumno:**Freya Melissa López Flores

**No. de cuenta:** A225952-0

**Profesor:** Lázaro Bustio Martínez

**Fecha de entrega:** 13/02/2023

**Objetivo:** El objetivo de este programa es solucionar las preguntas de la "Tarea clase práctica 7."

##**1. Generar un DataFrame con los datos de los cuatro archivos.**

In [ ]:
#IMPORTAMOS LAS LIBRERIAS CON LAS QUE TRABAJAREMOS
import pandas as pd
import numpy as np

from google.colab import files 
import io
import datetime as dt #librería para trabajar con fechas y horas

In [ ]:
#CARGAMOS LOS ARCHIVOS QUE USAREMOS
archivo_2016 = files.upload()

Saving emisiones-2016.csv to emisiones-2016.csv

In [ ]:
archivo_2017 = files.upload()

Saving emisiones-2017.csv to emisiones-2017.csv

In [ ]:
archivo_2018 = files.upload()

Saving emisiones-2018.csv to emisiones-2018.csv

In [ ]:
archivo_2019 = files.upload()

Saving emisiones-2019.csv to emisiones-2019.csv

In [ ]:
#LEEMOS LOS ARCHIVOS QUE CARGAMOS
a_2016=pd.read_csv(io.BytesIO(archivo_2016["emisiones-2016.csv"]),sep=";", header=0)
a_2017=pd.read_csv(io.BytesIO(archivo_2017["emisiones-2017.csv"]),sep=";", header=0)
a_2018=pd.read_csv(io.BytesIO(archivo_2018["emisiones-2018.csv"]),sep=";", header=0)
a_2019=pd.read_csv(io.BytesIO(archivo_2019["emisiones-2019.csv"]),sep=";", header=0)

In [ ]:
#JUNTAMOS LOS 4 ARCHIVOS EN UN DATAFRAME CON "CONCAT"
df = pd.concat([a_2016, a_2017, a_2018, a_2019])
df

,PROVINCIA,MUNICIPIO,ESTACION,MAGNITUD,PUNTO_MUESTREO,ANO,MES,D01,V01,D02,...,D27,V27,D28,V28,D29,V29,D30,V30,D31,V31
0,28,79,4,1,28079004_1_38,2016,1,8.0,V,7.0,...,9.0,V,7.0,V,8.0,V,9.0,V,9.0,V
1,28,79,4,1,28079004_1_38,2016,2,12.0,V,13.0,...,7.0,V,8.0,V,9.0,V,0.0,N,0.0,N
2,28,79,4,1,28079004_1_38,2016,3,11.0,V,10.0,...,8.0,V,7.0,V,8.0,V,10.0,V,8.0,V
3,28,79,4,1,28079004_1_38,2016,4,8.0,V,9.0,...,9.0,V,8.0,V,8.0,V,8.0,V,0.0,N
4,28,79,4,1,28079004_1_38,2016,5,7.0,V,8.0,...,7.0,V,7.0,V,7.0,V,7.0,V,7.0,V
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1831,28,79,60,14,28079060_14_6,2019,8,94.0,V,104.0,...,88.0,V,90.0,V,99.0,V,108.0,V,98.0,V
1832,28,79,60,14,28079060_14_6,2019,9,88.0,V,82.0,...,54.0,V,68.0,V,70.0,V,55.0,V,0.0,N
1833,28,79,60,14,28079060_14_6,2019,10,44.0,V,75.0,...,28.0,V,33.0,V,16.0,V,19.0,V,47.0,V
1834,28,79,60,14,28079060_14_6,2019,11,41.0,V,55.0,...,55.0,V,52.0,V,47.0,V,56.0,V,0.0,N
1835,28,79,60,14,28079060_14_6,2019,12,47.0,V,53.0,...,17.0,V,13.0,V,14.0,V,5.0,V,4.0,V

In [ ]:
df.shape

(7266, 69)

In [ ]:
df.to_csv('T9_emisiones.csv') #guardamos el df en un archivo tipo csv

##2. Filtrar las columnas del DataFrame para quedarse con las columnas ESTACION,MAGNITUD, AÑO, MES y las correspondientes a los días D01, D02, etc.

In [ ]:
cols=['ESTACION', 'MAGNITUD', 'ANO', 'MES'] #Son las columnas con las que queremos quedarnos
cols.extend([i for i in df if i.startswith('D')]) #de las columnas con las que me quedé les agregré la de los días
df= df[cols]
df

,ESTACION,MAGNITUD,ANO,MES,D01,D02,D03,D04,D05,D06,...,D22,D23,D24,D25,D26,D27,D28,D29,D30,D31
0,4,1,2016,1,8.0,7.0,6.0,6.0,7.0,6.0,...,10.0,11.0,11.0,13.0,12.0,9.0,7.0,8.0,9.0,9.0
1,4,1,2016,2,12.0,13.0,9.0,9.0,11.0,9.0,...,11.0,10.0,9.0,8.0,7.0,7.0,8.0,9.0,0.0,0.0
2,4,1,2016,3,11.0,10.0,9.0,9.0,7.0,8.0,...,8.0,8.0,9.0,9.0,9.0,8.0,7.0,8.0,10.0,8.0
3,4,1,2016,4,8.0,9.0,9.0,8.0,8.0,9.0,...,8.0,8.0,8.0,8.0,9.0,9.0,8.0,8.0,8.0,0.0
4,4,1,2016,5,7.0,8.0,9.0,9.0,8.0,8.0,...,7.0,7.0,8.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1831,60,14,2019,8,94.0,104.0,106.0,99.0,77.0,82.0,...,86.0,97.0,104.0,96.0,85.0,88.0,90.0,99.0,108.0,98.0
1832,60,14,2019,9,88.0,82.0,80.0,92.0,79.0,75.0,...,59.0,46.0,49.0,69.0,57.0,54.0,68.0,70.0,55.0,0.0
1833,60,14,2019,10,44.0,75.0,44.0,54.0,65.0,68.0,...,37.0,39.0,45.0,21.0,23.0,28.0,33.0,16.0,19.0,47.0
1834,60,14,2019,11,41.0,55.0,79.0,65.0,64.0,51.0,...,38.0,75.0,69.0,45.0,35.0,55.0,52.0,47.0,56.0,0.0
1835,60,14,2019,12,47.0,53.0,45.0,44.0,49.0,41.0,...,68.0,36.0,9.0,11.0,10.0,17.0,13.0,14.0,5.0,4.0

##3. Reestructurar el DataFrame para que los valores de los contaminantes de las columnas de los días aparezcan en una única columna.

In [ ]:
df = df.melt(id_vars=['ESTACION', 'MAGNITUD', 'ANO', 'MES'], var_name='DIA', value_name ='VALORES_CONTAMINANTES')
df

        ESTACION  MAGNITUD   ANO  MES  DIA  VALORES_CONTAMINANTES
0              4         1  2016    1  D01                    8.0
1              4         1  2016    2  D01                   12.0
2              4         1  2016    3  D01                   11.0
3              4         1  2016    4  D01                    8.0
4              4         1  2016    5  D01                    7.0
...          ...       ...   ...  ...  ...                    ...
225241        60        14  2019    8  D31                   98.0
225242        60        14  2019    9  D31                    0.0
225243        60        14  2019   10  D31                   47.0
225244        60        14  2019   11  D31                    0.0
225245        60        14  2019   12  D31                    4.0

[225246 rows x 6 columns]

To make analysis of data in table easier, we can reshape the data into a more computer-friendly form using Pandas in Python. Pandas.melt() is one of the function to do so.

Pandas.melt() unpivots a DataFrame from wide format to long format.

melt() function is useful to massage a DataFrame into a format where one or more columns are identifier variables, while all other columns, considered measured variables, are unpivoted to the row axis, leaving just two non-identifier columns, variable and value.

https://www.geeksforgeeks.org/python-pandas-melt/

##4. Añadir una columna con la fecha a partir de la concatenación del año, el mes y el día (usar el módulo datetime).

In [ ]:
df["DIA"]= df.DIA.str.strip('D') #.strip elimina cualquier caracter ya sea inicial o final
#Con la línea de arriba esamos eliminando la D al inicio de la columna DIA 
df['FECHA'] = df.DIA.apply(str) + '/' + df.MES.apply(str) + '/' + df.ANO.apply(str) #Concatenamos año, mes y día para crear la columna FECHA
df['FECHA'] = pd.to_datetime(df['FECHA'], format='%d/%m/%Y', errors='coerce', dayfirst=True, yearfirst=False)
df

        ESTACION  MAGNITUD   ANO  MES DIA  VALORES_CONTAMINANTES      FECHA
0              4         1  2016    1  01                    8.0 2016-01-01
1              4         1  2016    2  01                   12.0 2016-02-01
2              4         1  2016    3  01                   11.0 2016-03-01
3              4         1  2016    4  01                    8.0 2016-04-01
4              4         1  2016    5  01                    7.0 2016-05-01
...          ...       ...   ...  ...  ..                    ...        ...
225241        60        14  2019    8  31                   98.0 2019-08-31
225242        60        14  2019    9  31                    0.0        NaT
225243        60        14  2019   10  31                   47.0 2019-10-31
225244        60        14  2019   11  31                    0.0        NaT
225245        60        14  2019   12  31                    4.0 2019-12-31

[225246 rows x 7 columns]

Sobre datetime: https://www.geeksforgeeks.org/python-pandas-to_datetime/

https://stackoverflow.com/questions/37285365/valueerror-day-is-out-of-range-for-month
:

##5. Eliminar las filas con fechas no válidas (utilizar la función isnat del módulo numpy) y ordenar el DataFrame por estaciones contaminantes y fecha.

In [ ]:
df=df.drop(df[np.isnat(df.FECHA)].index)
#Con np.isnat reconocemos la fechas no válidas y con .drop las eliminamos 
df=df.sort_values(['ESTACION', 'MAGNITUD', 'FECHA']) #con .sort_values ordenamos el df por estaciones contaminantes y fecha
df

        ESTACION  MAGNITUD   ANO  MES DIA  VALORES_CONTAMINANTES      FECHA
0              4         1  2016    1  01                    8.0 2016-01-01
7266           4         1  2016    1  02                    7.0 2016-01-02
14532          4         1  2016    1  03                    6.0 2016-01-03
21798          4         1  2016    1  04                    6.0 2016-01-04
29064          4         1  2016    1  05                    7.0 2016-01-05
...          ...       ...   ...  ...  ..                    ...        ...
196181        60        14  2019   12  27                   17.0 2019-12-27
203447        60        14  2019   12  28                   13.0 2019-12-28
210713        60        14  2019   12  29                   14.0 2019-12-29
217979        60        14  2019   12  30                    5.0 2019-12-30
225245        60        14  2019   12  31                    4.0 2019-12-31

[221158 rows x 7 columns]

**np.isnat:**

With the help of numpy.isnat() method, we can get the boolean value as true if date defined in a np.datetime64() method is not a time by using numpy.isnat() method.
https://www.geeksforgeeks.org/python-numpy-isnat-method/ 

**.sort_value:**

https://www.geeksforgeeks.org/python-pandas-dataframe-sort_values-set-1/

##6. Mostrar por pantalla las estaciones y los contaminantes disponibles en el DataFrame.

In [ ]:
print("ESTACIONES:", df.ESTACION.unique(), "\nCONTAMINANTES:", df.MAGNITUD.unique())

ESTACIONES: [ 4  8 11 16 17 18 24 27 35 36 38 39 40 47 48 49 50 54 55 56 57 58 59 60]
CONTAMINANTES: [ 1  6  7  8 12  9 10 14 20 30 35 42 43 44]

**.unique**

Given a list, print all the unique numbers in any order.
https://www.geeksforgeeks.org/python-get-unique-values-list/

##7. Crear una función que reciba una estación, un contaminante y un rango de fechas y devuelva una serie con las emisiones del contaminante dado en la estación y rango de fechas dado.

In [ ]:
#creamos la función:
def Fun_Emi(estacion, contaminante, fecha1, fecha2):
    return df[(df.ESTACION == estacion) & (df.MAGNITUD == contaminante) & (df.FECHA >= fecha1) & (df.FECHA <= fecha2)].sort_values('FECHA').VALORES_CONTAMINANTES
#Establecemos que df.FECHA se encuentre entre las dos fechas dadas, las ordenamos y mostramos los valores contaminantes ya ordenados.

In [ ]:
Fun_Emi(56, 8, dt.datetime.strptime('2019/02/12', '%Y/%m/%d'), dt.datetime.strptime('2019/05/17', '%Y/%m/%d'))

86905      71.0
94171      95.0
101437     90.0
108703    103.0
115969     76.0
          ...
94174      67.0
101440     74.0
108706     70.0
115972     55.0
123238     24.0
Name: VALORES_CONTAMINANTES, Length: 95, dtype: float64

##8. Mostrar un resumen descriptivo (mínimo, máximo, media, etc.) para cada contaminante.

In [ ]:
resumen=df.groupby("MAGNITUD").VALORES_CONTAMINANTES.describe() 
#Agrupamos cada tipo de contaminante con groupby y con describe sacamos el resumen descriptivo
resumen

            count       mean         std   min    25%    50%    75%       max
MAGNITUD
1         14610.0   7.428953    7.012504  0.00   4.00   7.00  10.00    610.00
6         14610.0   0.350233    0.215935  0.00   0.20   0.30   0.40     14.90
7         35064.0  20.446412  135.123509  0.00   4.00   9.00  23.00  24742.00
8         35064.0  37.677618   20.118050  0.00  22.00  35.00  50.00    148.00
9          8948.0  10.087729   10.643591  0.00   6.00   9.00  13.00    850.00
10        17897.0  18.772923   35.723619  0.00  10.00  16.00  24.00   4481.00
12        35064.0  67.959417   61.443940  0.00  29.00  48.00  84.00   1005.00
14        20454.0  49.941772   24.753120  0.00  31.00  52.00  69.00    336.00
20         8766.0   2.364944    4.236706  0.00   0.80   1.60   2.80    195.00
30         8766.0   0.531371    0.538180  0.00   0.20   0.40   0.70     15.10
35         8766.0   0.479751    1.183618  0.00   0.10   0.20   0.50     35.70
42         4383.0   1.400897    0.251836 -0.01   1.25   1.38   1.54      3.09
43         4383.0   1.292923    0.230898 -0.14   1.17   1.28   1.43      2.77
44         4383.0   0.108941    0.068776  0.00   0.06   0.10   0.14      1.31

##9. Mostrar un resumen descriptivo para cada contaminante por distritos.

In [ ]:
resumen2 = df.groupby(["ESTACION", "MAGNITUD"]).VALORES_CONTAMINANTES.describe()
resumen2

                    count       mean        std  min   25%   50%    75%    max
ESTACION MAGNITUD
4        1         1461.0   7.329911  16.379050  1.0   4.0   7.0    9.0  610.0
         6         1461.0   0.411499   0.172902  0.1   0.3   0.4    0.5    1.3
         7         1461.0  31.939767  37.667968  0.0   8.0  16.0   42.0  239.0
         8         1461.0  44.398357  17.766063  0.0  31.0  43.0   55.0  105.0
         12        1461.0  93.341547  72.436531  0.0  44.0  69.0  119.0  467.0
...                   ...        ...        ...  ...   ...   ...    ...    ...
60       7         1461.0  12.326489  19.593109  1.0   2.0   4.0   12.0  151.0
         8         1461.0  31.125941  18.101896  3.0  18.0  27.0   41.0  101.0
         10        1461.0  17.033539  12.205022  1.0   9.0  14.0   21.0  215.0
         12        1461.0  50.023956  45.933843  6.0  22.0  33.0   60.0  328.0
         14        1461.0  60.718001  26.309952  4.0  42.0  65.0   81.0  119.0

[153 rows x 8 columns]

##10. Crear una función que reciba una estación y un contaminante y devuelva un resumen descriptivo de las emisiones del contaminante indicado en la estación indicada.

In [ ]:
#La función deberá buscar dentro de las estaciones y contaminantes los datos ingresados para mostrar su descripción 
def Res(estacion, contaminante):
    return df[(df.ESTACION == estacion) & (df.MAGNITUD == contaminante)].VALORES_CONTAMINANTES.describe()

print('Resumen Descriptivo: \n', Res(16, 8),'\n', sep='')

Resumen Descriptivo:
count    1461.000000
mean       37.699521
std        17.539448
min         6.000000
25%        25.000000
50%        35.000000
75%        49.000000
max       110.000000
Name: VALORES_CONTAMINANTES, dtype: float64

##11.Crear una función que devuelva las emisiones medias mensuales de un contaminante y un año dados para todas las estaciones.

In [ ]:
 def Emi_Medias_Mens(contaminante, anio):
    return df[(df.ANO == anio) & (df.MAGNITUD == contaminante)].groupby(['ESTACION', 'MES']).VALORES_CONTAMINANTES.mean().unstack('MES')
    #.unstack: para que vaya pivoteando entre los meses (1:12)

Emi_Medias_Mens(8, 2019)

MES,1,2,3,4,5,6,7,8,9,10,11,12
ESTACION,,,,,,,,,,,,
4,61.129032,62.000000,44.677419,36.033333,33.451613,36.700000,36.838710,34.064516,35.400000,33.451613,21.800000,40.806452
8,74.516129,77.071429,57.064516,48.466667,43.032258,41.933333,36.387097,24.612903,45.233333,55.000000,42.033333,49.870968
11,58.516129,59.571429,37.709677,32.066667,26.064516,31.733333,33.451613,28.322581,36.966667,48.451613,31.800000,47.612903
16,54.387097,56.892857,35.451613,27.933333,20.354839,24.666667,25.258065,24.548387,31.266667,41.935484,29.500000,40.677419
17,65.967742,70.142857,43.161290,29.400000,22.548387,25.133333,27.161290,29.322581,36.933333,47.774194,30.566667,44.516129
18,55.161290,54.821429,35.645161,24.300000,19.967742,21.033333,22.322581,23.419355,25.833333,41.225806,25.400000,39.193548
24,37.516129,38.464286,21.645161,13.100000,10.806452,12.000000,13.322581,13.903226,20.600000,27.000000,12.166667,26.258065
27,47.580645,48.214286,35.709677,27.566667,22.903226,26.233333,27.032258,31.677419,35.966667,49.000000,30.133333,45.774194
35,54.548387,51.857143,31.903226,21.700000,22.548387,26.033333,35.322581,33.096774,37.533333,45.193548,30.133333,41.483871
36,58.870968,58.678571,37.645161,29.333333,21.354839,24.800000,25.677419,25.935484,31.500000,43.838710,32.300000,43.354839
38,62.193548,59.357143,38.032258,29.333333,25.935484,25.366667,22.096774,21.161290,37.033333,47.064516,29.200000,45.870968
39,63.354839,62.214286,37.483871,25.566667,19.483871,25.200000,25.483871,24.870968,30.466667,47.290323,27.133333,42.774194
40,58.967742,57.357143,36.387097,28.433333,21.967742,24.033333,26.419355,26.548387,34.733333,44.580645,30.966667,41.709677
47,53.548387,52.571429,36.322581,23.600000,21.354839,18.966667,23.903226,26.806452,33.666667,43.645161,26.733333,39.193548
48,55.709677,57.178571,34.677419,26.466667,17.967742,24.633333,24.903226,20.870968,27.333333,43.967742,33.666667,43.000000
49,45.580645,42.035714,25.870968,17.366667,14.354839,13.900000,16.129032,16.322581,19.433333,31.838710,22.200000,33.935484
50,57.741935,56.214286,36.741935,32.466667,24.000000,30.233333,28.967742,26.258065,32.233333,44.709677,31.766667,41.709677
54,60.774194,59.321429,38.354839,27.900000,24.645161,22.066667,23.806452,26.225806,34.266667,46.967742,32.900000,45.967742
55,63.548387,61.750000,44.161290,31.233333,25.419355,26.633333,26.064516,28.225806,32.833333,45.000000,27.833333,44.064516
56,77.483871,82.428571,61.064516,46.900000,44.032258,41.100000,45.838710,44.580645,52.100000,57.225806,35.133333,51.903226
57,53.967742,52.321429,31.290323,25.000000,17.354839,20.766667,21.903226,21.677419,25.900000,37.806452,26.000000,38.193548
58,24.774194,24.071429,15.483871,11.166667,9.483871,12.266667,12.322581,12.935484,15.433333,21.645161,11.900000,18.935484
59,39.064516,40.964286,25.322581,19.666667,13.741935,16.833333,14.225806,14.774194,22.866667,35.290323,23.400000,32.387097
60,42.032258,44.750000,25.129032,21.033333,14.580645,18.233333,22.000000,16.096774,19.466667,20.806452,15.733333,42.870968

.unstack

Pandas Unstack is a function that pivots the level of the indexed columns in a stacked dataframe.
https://www.geeksforgeeks.org/pandas-groupby-unstack/

##12. Crear un función que reciba una estación de medición y devuelva un DataFrame con las medias mensuales de los distintos tipos de contaminantes.

In [ ]:
def DF_Medias_Cont(estacion):
  return df[(df.ESTACION == estacion)].groupby(['MAGNITUD', 'MES']).VALORES_CONTAMINANTES.mean().unstack('MES')
DF_Medias_Cont(8)

MES,1,2,3,4,5,6,7,8,9,10,11,12
MAGNITUD,,,,,,,,,,,,
1,11.016129,10.168142,9.524194,7.616667,8.588710,9.716667,8.088710,6.137097,7.433333,6.879032,7.266667,8.185484
6,0.456452,0.404425,0.324194,0.324167,0.294355,0.281667,0.246774,0.246774,0.360000,0.438710,0.466667,0.510484
7,53.653226,36.000000,23.403226,15.716667,13.991935,13.208333,12.104839,8.637097,19.916667,39.177419,44.725000,60.258065
8,66.540323,63.362832,55.475806,50.075000,48.887097,49.883333,48.467742,39.991935,56.983333,63.846774,61.108333,65.395161
9,12.596774,11.424779,10.104839,7.625000,7.629032,10.683333,12.306452,12.532258,10.991667,10.572581,9.541667,13.177419
10,19.766129,23.345133,17.112903,14.416667,14.903226,24.508333,26.201613,24.314516,23.333333,21.806452,16.175000,19.951613
12,148.774194,118.424779,91.370968,74.150000,70.314516,70.125000,67.096774,53.233871,87.408333,123.951613,129.675000,157.725806
14,22.233871,31.407080,46.483871,54.258333,57.629032,60.266667,65.169355,58.870968,49.383333,31.524194,25.683333,18.669355
20,3.435484,2.879646,2.332258,1.893333,2.213710,2.441667,2.217742,2.286290,3.617500,4.754032,3.795833,3.855645
30,1.111290,0.937168,0.776613,0.571667,0.512903,0.485000,0.451613,0.421774,0.670833,0.966129,0.980833,1.162097
35,0.503226,0.429204,0.358065,0.300000,0.303226,0.336667,0.325806,0.679839,0.915000,1.402419,0.730000,0.762097
42,1.685968,1.609469,1.581774,1.535000,1.493871,1.512667,1.489919,1.387097,1.571917,1.635968,1.668833,1.760968
43,1.563952,1.494071,1.477419,1.444250,1.406855,1.406167,1.392984,1.267500,1.428250,1.487177,1.554833,1.634839
44,0.122903,0.116726,0.104839,0.091917,0.088387,0.107833,0.098145,0.120323,0.144917,0.149677,0.115083,0.127500